---
title: "Omega tables"
output: pdf_document
header-includes:
  - \usepackage{upgreek}
date: "2023-04-06"
---

```{r setup, include=FALSE}

library(easypackages)
packages <- c('tidyverse', 'RColorBrewer', 'parallel', 'data.table', 'kableExtra', 'ggtext', 'egg', 'ggbrace', 'cowplot', 'nonlinSimsAnalysis', 'nonlinSims', 'knitr', 'devtools')
libraries(packages)

exp_1_raw <- nonlinSimsAnalysis:::convert_raw_var_to_sd(raw_data = read_csv('data/exp_1_data.csv')) %>%
  mutate_at(.vars = c("number_measurements", "measurement_spacing", "midpoint"), factor)

exp_3_raw <-nonlinSimsAnalysis:::convert_raw_var_to_sd(raw_data = read_csv('data/exp_3_data.csv')) %>%
  mutate_at(.vars = c("number_measurements", "time_structuredness", "sample_size"), factor)

load_all()

```


\landscape
```{r echo=F}
print_bias_var_omega_table(exp_data = exp_1_raw, target_col = 'measurement_spacing', target_value = 'equal', 
ind_vars = c('number_measurements', 'midpoint'), 
ind_var_acronyms = c('NM', 'NC', 'NM x NC'), 
caption = 'Partial $\\upomega^2$ Values for Manipulated Variables With Equal Spacing in Experiment 1',
footnote = '\\\\textit{Note. }NM = number of measurements $\\\\in$ \\\\{5, 7, 9, 11\\\\}, NC = nature of change (population value set for $\\\\upbeta_{fixed}$ $\\\\in$ \\\\{80, 180, 280\\\\}), NM x NC = interaction between number of measurements and population value set for $\\\\upbeta_{fixed}$. $\\\\upbeta_{fixed}$ = fixed-effect days-to-halfway elevation parameter,
           $\\\\upgamma_{fixed}$ = fixed-effect triquarter-halfway delta parameter, 
           $\\\\upbeta_{random}$ = random-effect days-to-halfway elevation parameter, and 
           $\\\\upgamma_{random}$ = random-effect triquarter-halfway delta parameter.', 
parameter_labels = c('$\\upbeta_{fixed}$ (Figure \\ref{fig:exp1_plot_equal}A)',
                     '$\\upbeta_{random}$ (Figure \\ref{fig:exp1_plot_equal}B)',
                     '$\\upgamma_{fixed}$ (Figure \\ref{fig:exp1_plot_equal}C)',
                     '$\\upgamma_{random}$ (Figure \\ref{fig:exp1_plot_equal}D)'))


print_bias_var_omega_table(exp_data = exp_1_raw, target_col = NA, target_value = 'equal', 
ind_vars = c('number_measurements', 'midpoint', 'measurement_spacing'), 
ind_var_acronyms = c('NM', 'NC', 'MS', 'NM x NC','NM x MS', 'NC x MS', 'NM x NC x MS'), 
caption = 'Partial $\\upomega^2$ Values for Manipulated Variables With Equal Spacing in Experiment 1',
footnote = '\\\\textit{Note. }NM = number of measurements $\\\\in$ \\\\{5, 7, 9, 11\\\\}, NC = nature of change (population value set for $\\\\upbeta_{fixed}$ $\\\\in$ \\\\{80, 180, 280\\\\}), NM x NC = interaction between number of measurements and population value set for $\\\\upbeta_{fixed}$. $\\\\upbeta_{fixed}$ = fixed-effect days-to-halfway elevation parameter,
           $\\\\upgamma_{fixed}$ = fixed-effect triquarter-halfway delta parameter, 
           $\\\\upbeta_{random}$ = random-effect days-to-halfway elevation parameter, and 
           $\\\\upgamma_{random}$ = random-effect triquarter-halfway delta parameter.', 
parameter_labels = c('$\\upbeta_{fixed}$ (Figure \\ref{fig:exp1_plot_equal}A)',
                     '$\\upbeta_{random}$ (Figure \\ref{fig:exp1_plot_equal}B)',
                     '$\\upgamma_{fixed}$ (Figure \\ref{fig:exp1_plot_equal}C)',
                     '$\\upgamma_{random}$ (Figure \\ref{fig:exp1_plot_equal}D)'))


```
