---
title: "tutorial_analysis"
output: pdf_document
vignette: >
  %\VignetteIndexEntry{tutorial_analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
header-includes:
  - \usepackage{upgreek}  #required for non-italicized Greek letters
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r package_loading, echo=F}
library(easypackages)
packages <- c('nonlinSimsAnalysis', 'tidyverse', 'data.table', 'parallel', 'devtools', 'ggtext', 'egg', 'kableExtra')
libraries(packages)

load_all()
```

```{r pre_knitting_setup, echo=F, eval=F}
#code should be computed before knitting to decrease knitting time 
#load data from experiments
exp_1 <- read_csv(file = 'data/exp_1A.csv') 
exp_2 <- read_csv(file = 'data/exp_2.csv')
exp_3 <- read_csv(file = 'data/exp_3.csv')

#data cleaning procedure for each data set
#filter out values for each parameter under each condition 
exp_1_filtered <- remove_outliers(data = exp_1)
exp_2_filtered <- remove_outliers(data = exp_2)
exp_3_filtered <- remove_outliers(data = exp_3)
  
#convert variance values to SD values for random effect parameters 
exp_1_cleaned <- convert_var_to_sd(data = exp_1_filtered)
exp_2_cleaned <- convert_var_to_sd(data = exp_2_filtered)
exp_3_cleaned <- convert_var_to_sd(data = exp_3_filtered)

#compute summary values 
param_summary_exp_1 <- compute_parameter_summary(data = exp_1_cleaned, exp_num = 1)
param_summary_exp_2 <- compute_parameter_summary(data = exp_2_cleaned, exp_num = 2)
param_summary_exp_3 <- compute_parameter_summary(data = exp_3_cleaned, exp_num = 3)

#save parameter summary files as RData files so that metadata are correctly stored (e.g., factor levels, variable types)
saveRDS(object = param_summary_exp_1, file = 'data/param_summary_exp_1.RData')
saveRDS(object = param_summary_exp_2, file = 'data/param_summary_exp_2.RData')
saveRDS(object = param_summary_exp_3, file = 'data/param_summary_exp_3.RData')
```

```{r obsolete_metadata_storing_importing, echo=F, eval=F}
#store classes of each column 
col_types_exp_1 <- unlist(lapply(X = param_summary_exp_1, FUN = class))
col_types_exp_2 <- unlist(lapply(X = param_summary_exp_2, FUN = class))
col_types_exp_3 <- unlist(lapply(X = param_summary_exp_3, FUN = class))

#create data.frame that stores classes of data columns 
col_types_df <- data.frame('exp_num' = c(rep(x = 1, times = length(col_types_exp_1)),
                                         rep(x = 2, times = length(col_types_exp_2)),
                                         rep(x = 3, times = length(col_types_exp_3))), 
                           'variable_types' = c(col_types_exp_1, col_types_exp_2, col_types_exp_3))

#create data fame that stores levels of factor variables 
exp_1_factor_levels <- extract_factor_levels(param_summary_data = param_summary_exp_1)
exp_2_factor_levels <- extract_factor_levels(param_summary_data = param_summary_exp_2)
exp_3_factor_levels <- extract_factor_levels(param_summary_data = param_summary_exp_3)

#write summary data  
write_csv(x = param_summary_exp_1, file = 'data/param_summary_exp_1.csv')
write_csv(x = param_summary_exp_2, file = 'data/param_summary_exp_2.csv')
write_csv(x = param_summary_exp_3, file = 'data/param_summary_exp_3.csv')

#write meta data + data for factor levels 
write_csv(x = col_types_df, file = 'data/col_types.csv')
write_csv(x = exp_1_factor_levels, file = 'data/exp_1_factor_levels.csv')
write_csv(x = exp_2_factor_levels, file = 'data/exp_2_factor_levels.csv')
write_csv(x = exp_3_factor_levels, file = 'data/exp_3_factor_levels.csv')

#read in .csv files with experimental data already in summarized version 
col_types_df <-read_csv(file = 'data/col_types.csv')
exp_1_factor_levels <- read_csv(file = 'data/exp_1_factor_levels.csv')
exp_2_factor_levels <- read_csv(file = 'data/exp_2_factor_levels.csv')
exp_3_factor_levels <- read_csv(file = 'data/exp_3_factor_levels.csv')

#import summary data files 
param_summary_exp_1 <- read.csv(file = 'data/param_summary_exp_1.csv', colClasses = col_types_df$variable_types[col_types_df$exp_num == 1])
param_summary_exp_2 <- read.csv(file = 'data/param_summary_exp_2.csv',  colClasses = col_types_df$variable_types[col_types_df$exp_num == 2])
param_summary_exp_3 <- read.csv(file = 'data/param_summary_exp_3.csv', colClasses = col_types_df$variable_types[col_types_df$exp_num == 3])

#relevel factors columns 
param_summary_exp_1 <- relevel_factors(param_summary_data = param_summary_exp_1, factor_levels_df = exp_1_factor_levels)
param_summary_exp_2 <- relevel_factors(param_summary_data = param_summary_exp_2, factor_levels_df = exp_2_factor_levels)
param_summary_exp_3 <- relevel_factors(param_summary_data = param_summary_exp_3, factor_levels_df = exp_3_factor_levels)
```

```{r knitting_setup, echo = F}
param_summary_exp_1 <- readRDS(file = 'data/param_summary_exp_1.RData')
param_summary_exp_2 <- readRDS(file = 'data/param_summary_exp_2.RData')
param_summary_exp_3 <- readRDS(file = 'data/param_summary_exp_3.RData')

#create condition summary data sets 
cond_summary_exp_1 <- compute_condition_summary(param_summary_data = param_summary_exp_1, facet_var = 'measurement_spacing', 
                          ind_vars = c('number_measurements', 'measurement_spacing', 'midpoint'))
cond_summary_exp_2 <- compute_condition_summary(param_summary_data = param_summary_exp_2, facet_var = 'measurement_spacing', 
                  ind_vars = c('number_measurements', 'measurement_spacing', 'sample_size'))
cond_summary_exp_3 <- compute_condition_summary(param_summary_data = param_summary_exp_3, facet_var = 'time_structuredness', 
                          ind_vars = c('number_measurements', 'sample_size', 'time_structuredness'))

#create analytical versions of summary data 
exp_1_analytical <- generate_likert_days_data_sets(summary_data = param_summary_exp_1, exp_num = 1)
exp_2_analytical <- generate_likert_days_data_sets(summary_data = param_summary_exp_2, exp_num = 2)
exp_3_analytical <- generate_likert_days_data_sets(summary_data = param_summary_exp_3, exp_num = 3)
```

```{r echo=F}
exp_1_tables <- create_table_data_sets(param_summary_data = param_summary_exp_1, wide_var = 'midpoint', 
                       first_col = 'measurement_spacing', second_col = 'number_measurements')

exp_2_tables <- create_table_data_sets(param_summary_data = param_summary_exp_2, wide_var = 'sample_size', 
                       first_col = 'measurement_spacing', second_col = 'number_measurements')

exp_3_tables <- create_table_data_sets(param_summary_data = param_summary_exp_3, wide_var = 'sample_size', 
                       first_col = 'time_structuredness', second_col = 'number_measurements') %>%


print_param_table(table_ready_data = exp_1_tables$estimate_table, parameter_name = 'theta', 
            caption_name = 'Parameter Estimate Values in Experiment 1', 
            col_header_name = c('$\\\\uptheta_{fixed}$(lower plateau)', '$\\\\uptheta_{random}$(lower plateau)'), 
            IV_names =  c('Measurement spacing', 'Number of measurements'), 
            column_names = c(80, 180, 280))


print_param_table(table_ready_data = exp_2_tables$estimate_table, parameter_name = 'alpha', 
            caption_name = 'Parameter Estimate Values in Experiment 2', 
            col_header_name = c('$\\\\uptheta_{fixed}$(lower plateau)', '$\\\\uptheta_{random}$(lower plateau)'), 
            IV_names =  c('Measurement spacing', 'Number of measurements'), 
            column_names = c(30, 50, 100, 200, 500, 1000))


print_param_table(table_ready_data = exp_1_tables$removed_value_table, parameter_name = 'alpha', 
            caption_name = 'Number of Removed Values for Each Parameter Estimate in Experiment 1', 
            col_header_name = c('$\\\\uptheta_{fixed}$(lower plateau)', '$\\\\uptheta_{random}$(lower plateau)'), 
            IV_names =  c('Measurement spacing', 'Number of measurements'), 
            column_names = c(80, 180, 280))






```

```{r exp2-theta-param-est, echo=F}
print_param_table(table_ready_data = exp_2_tables$estimate_table, parameter_name = 'theta', 
            caption_name = 'Parameter Values Estimated in Experiment 2', 
            col_header_name = c('$\\\\uptheta_{fixed}$(lower plateau)', '$\\\\uptheta_{random}$(lower plateau)'), 
            IV_names =  c('Measurement Spacing', 'Number of Measurements'), 
            column_names = c("30", "50", "100", "200", "500", "1000"))
```

\addtocounter{table}{-1}
```{r exp2-alpha-param-est, echo=F}
print_param_table(table_ready_data = exp_2_tables$estimate_table, parameter_name = 'theta', 
            caption_name = 'Parameter Values Estimated in Experiment 2 (continued)', 
            col_header_name = c('$\\\\upalpha_{fixed}$(upper plateau)', '$\\\\upalpha_{random}$(upper plateau)'), 
            IV_names =  c('Measurement Spacing', 'Number of Measurements'), 
            column_names = c("30", "50", "100", "200", "500", "1000"))
```

\addtocounter{table}{-1}
```{r exp2-beta-param-est, echo=F}
print_param_table(table_ready_data = exp_2_tables$estimate_table, parameter_name = 'beta', 
            caption_name = 'Parameter Values Estimated in Experiment 2 (continued)', 
            col_header_name = c('$\\\\upbeta_{fixed}$(midpoint)', '$\\\\upbeta_{random}$(midpoint)'), 
            IV_names =  c('Measurement Spacing', 'Number of Measurements'), 
            column_names = c("30", "50", "100", "200", "500", "1000"))
```

\addtocounter{table}{-1}
```{r exp2-gamma-param-est, echo=F}
print_param_table(table_ready_data = exp_2_tables$estimate_table, parameter_name = 'gamma', 
            caption_name = 'Parameter Values Estimated in Experiment 2 (continued)', 
            col_header_name = c('$\\\\upgamma_{fixed}$(midpoint)', '$\\\\upgamma_{random}$(midpoint)'), 
            IV_names =  c('Measurement Spacing', 'Number of Measurements'), 
            column_names = c("30", "50", "100", "200", "500", "1000"))
```

\addtocounter{table}{-1}
```{r exp2-epsilon-param-est, echo=F}
print_param_table(table_ready_data = exp_2_tables$estimate_table, parameter_name = 'epsilon', 
            caption_name = 'Parameter Values Estimated in Experiment 2 (continued)', 
            col_header_name = c('$\\\\upepsilon$(error)'), 
            IV_names =  c('Measurement Spacing', 'Number of Measurements'), 
            column_names = c("30", "50", "100", "200", "500", "1000"))
```

