---
format          : "pandoc"
header-includes:
  - \usepackage{nccmath}
  - \usepackage{caption}
  - \usepackage{textcomp} #for copyright symbol on title page
  - \usepackage{longtable}
  - \usepackage{makecell}
  - \usepackage[section]{placeins}
  - \usepackage{setspace}
  - \usepackage{biblatex}
  - \usepackage{booktabs}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{xcolor}
  - \usepackage{amsthm} 
  - \usepackage{amsmath} ##needed for argmax
  - \usepackage{bm}  #thicker bold in math 
  - \usepackage{setspace} #needed to doublespace caption text (using \doublespacing)
  - \usepackage[labelfont = {bf, up}]{caption} 
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \usepackage{upgreek}  #required for non-italicized Greek letters
  - \usepackage{subcaption}
  - \captionsetup[figure]{labelfont={normalfont, bf}, singlelinecheck=false, labelsep=newline}
  - \DeclareCaptionFont{figCaptionFont}{\fontfamily{phv}\doublespacing} #sets caption font to sans serif font of Helvetica 
  - \DeclareCaptionFont{figCaptionSize}{\fontsize{11pt}{13.2pt}\selectfont} #set caption font size to footnote 
  - \DeclareCaptionFont{figCaptionStyle}{\textup}  #set caption font to non-italicized font  
  - \DeclareCaptionLabelSeparator{captionSep}{\newline} #separates figure label and figure title with required white space
  - \captionsetup[figure]{labelfont={figCaptionStyle, bf}, font = {figCaptionFont,figCaptionSize, figCaptionStyle}, labelsep = captionSep, justification= raggedright}
 
    
  - \DeclareCaptionFont{CaptionFont}{\fontfamily{phv}} %sets caption font to sans serif font of Helvetica (used in Tables and Figures)
  - \DeclareCaptionFont{titleSize}{\fontsize{11pt}{13.2pt}\fontfamily{phv}\selectfont}
  - \DeclareCaptionLabelSeparator{captionSep}{\newline} %separates figure label and figure title with newlin
  - \captionsetup[table]{labelfont={CaptionFont, titleSize, bf}, textfont = {it, CaptionFont, titleSize}, labelsep = captionSep, justification= raggedright, singlelinecheck=off, skip = 0pt}

  - \AtBeginEnvironment{ThreePartTable}{\vspace{0.4cm}\par\setstretch{1.5}\fontfamily{phv}\fontsize{10.5pt}{12pt}\selectfont\relax}
  - \AtBeginEnvironment{TableNotes}{\setstretch{1.5}\fontfamily{phv}\fontsize{10pt}{12pt}\selectfont}

#set table line widths
  - \setlength\cmidrulewidth{1pt} %line thickness of lines within table and in multi-row headers
  - \setlength\lightrulewidth{1pt} %line thickness of bottom line in header

#environment numbering 
  - \setcounter{section}{0} 
  - \makeatletter \renewcommand\thesection{}\renewcommand\thesubsection{\@arabic\c@section.\@arabic\c@subsection} \makeatother

#set table line widths 
  - \setlength\cmidrulewidth{1pt} #line thickness of lines within table and in multi-row headers
  - \setlength\lightrulewidth{1pt} #line thickness of bottom line in header 

  - \newtheorem{theorem}{Theorem}
  - \newtheorem{example}[theorem]{Example}
  - \renewcommand\theadfont{} #sets cell font to be same as table font 
  
  #set figure title text
  - \newcommand{\figurefootnote}{\raggedright\linespread{2}\fontfamily{phv}\fontsize{9.5pt}{11.4pt}\selectfont \textit{Note. }}
  
  #table of contents settings 
  - \setcounter{tocdepth}{5} #
  - \setcounter{secnumdepth}{5} #set depth of header that will be numbered in the text and in the table of contents

  #modifies heading levels of 4-5 to follow apa7
  -  |
    \makeatletter
    
    \renewcommand\paragraph{% 
     \@startsection{paragraph}%
      {4}%
      {\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-0.5em}%
      {\normalfont\normalsize\bfseries\typesectitle}
    }
    
      
     \renewcommand\subparagraph{%
      \@startsection{subparagraph}%
      {5}%
      {\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-0.5em}%
      {\normalfont\normalsize\bfseries\itshape\typesectitle}}
    \makeatother
floatsintext      : yes
linkcolor         : blue
figsintext        : yes 
figurelist        : yes
tablelist         : no
footnotelist      : no

linenumbers       : yes
mask              : no
draft             : no
documentclass     : "apa7"
csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
classoption       : "man"        
output: 
  papaja::apa6_pdf:
    toc: true
    toc_depth: 5
    keep_tex: TRUE

editor_options: 
  markdown: 
    wrap: 72
---


```{r package_loading_1, include=F}
#load packages'
library(easypackages)
packages <- c('devtools','tidyverse', 'RColorBrewer', 'parallel', 'data.table', 'kableExtra', 'ggtext', 'egg', 'nonlinSims','papaja', 'ggbrace', 'cowplot')
libraries(packages)
load_all()
```

```{r knitting_setup_1, echo=F, message = F, warning = F}
#import raw data files (needed for computing variances)
exp_1_raw <- convert_raw_var_to_sd(raw_data = read_csv('data/exp_1_data.csv')) %>%
  mutate_at(.vars = c("number_measurements", "measurement_spacing", "midpoint"), factor)
  
exp_2_raw <-convert_raw_var_to_sd(raw_data = read_csv('data/exp_2_data.csv')) %>%
  mutate_at(.vars = c("number_measurements", "measurement_spacing", "sample_size"), factor)

exp_3_raw <-convert_raw_var_to_sd(raw_data = read_csv('data/exp_3_data.csv')) %>%
  mutate_at(.vars = c("number_measurements", "time_structuredness", "sample_size"), factor)

#unfiltered data 
param_summary_exp_1 <- readRDS(file = 'data/uf_param_summary_exp_1.RData')
param_summary_exp_2 <- readRDS(file = 'data/uf_param_summary_exp_2.RData')
param_summary_exp_3 <- readRDS(file = 'data/uf_param_summary_exp_3.RData')

#create analytical versions of summary data + converts vars to sds
exp_1_analytical <- generate_likert_days_data_sets(summary_data = param_summary_exp_1, exp_num = '1')
exp_2_analytical <- generate_likert_days_data_sets(summary_data = param_summary_exp_2, exp_num = '2')
exp_3_analytical <- generate_likert_days_data_sets(summary_data = param_summary_exp_3, exp_num = '3')

combined_analytical_exp_1 <- rbind(exp_1_analytical$likert, exp_1_analytical$days)
combined_analytical_exp_2 <- rbind(exp_2_analytical$likert, exp_2_analytical$days)
combined_analytical_exp_3 <- rbind(exp_3_analytical$likert, exp_3_analytical$days)

#create condition summary data sets 
cond_summary_exp_1 <- compute_condition_summary(param_summary_data = combined_analytical_exp_1, facet_var = 'measurement_spacing', 
                          ind_vars = c('number_measurements', 'measurement_spacing', 'midpoint'))
cond_summary_exp_2 <- compute_condition_summary(param_summary_data = combined_analytical_exp_2, facet_var = 'measurement_spacing', 
                  ind_vars = c('number_measurements', 'measurement_spacing', 'sample_size'))

cond_summary_exp_3 <- compute_condition_summary(param_summary_data = combined_analytical_exp_3, facet_var = 'time_structuredness', 
                          ind_vars = c('number_measurements', 'sample_size', 'time_structuredness'))

```

```{r pre_knitting_setup_unfiltered_1, echo=F, eval=F, include=F}
#code should be computed before knitting to decrease knitting time 
#load data from experiments
exp_1 <- read_csv(file = 'data/exp_1_data.csv') %>% filter(code == 0)
exp_2 <- read_csv(file = 'data/exp_2_data.csv')
exp_3 <- read_csv(file = 'data/exp_3_data.csv')

exp_1_ordered <- order_param_spacing_levels(data = exp_1_long)


compute_parameter_summary(data = exp_1, exp_num = '1')

param_summary_exp_1 <- compute_parameter_summary(data = exp_1, exp_num = 1)
param_summary_exp_2 <- compute_parameter_summary(data = exp_2, exp_num = 2)
param_summary_exp_3 <- compute_parameter_summary(data = exp_3, exp_num = 3)

#necessary factor conversions 
param_summary_exp_1$number_measurements <- factor(param_summary_exp_1$number_measurements, levels = c(5, 7, 9,11))
param_summary_exp_1$midpoint <- factor(param_summary_exp_1$midpoint, levels = c(80, 180,280))

param_summary_exp_2$number_measurements <- factor(param_summary_exp_2$number_measurements, levels = c(5, 7, 9,11))
param_summary_exp_2$sample_size <- factor(param_summary_exp_2$sample_size, levels = c(30, 50, 100, 200, 500, 1000))

param_summary_exp_3$number_measurements <- factor(param_summary_exp_3$number_measurements, levels = c(5, 7, 9,11))
param_summary_exp_3$sample_size <- factor(param_summary_exp_3$sample_size, levels = c(30, 50, 100, 200, 500, 1000))

#write data sets 
#save parameter summary files as RData files so that metadata are correctly stored (e.g., factor levels, variable types)
saveRDS(object = param_summary_exp_1, file = 'data/uf_param_summary_exp_1.RData')
saveRDS(object = param_summary_exp_2, file = 'data/uf_param_summary_exp_2.RData')
saveRDS(object = param_summary_exp_3, file = 'data/uf_param_summary_exp_3.RData')
```


```{r exp-table-generation, echo=F}
exp_1_tables <- nonlinSimsAnalysis:::create_table_data_sets(param_summary_data = param_summary_exp_1, 
                                       wide_var = 'midpoint', first_col = 'measurement_spacing', second_col = 'number_measurements')
  
exp_2_tables <- nonlinSimsAnalysis:::create_table_data_sets(param_summary_data = param_summary_exp_2, 
                                       wide_var = 'sample_size', first_col = 'measurement_spacing', second_col = 'number_measurements')

exp_3_tables <- nonlinSimsAnalysis:::create_table_data_sets(param_summary_data = param_summary_exp_3, 
                                       wide_var = 'sample_size', first_col = 'time_structuredness', second_col = 'number_measurements') 

#remove measurement spacing columns 
col_to_remove <- which(str_detect(string = names(exp_3_tables$estimate_table), pattern = 'measurement_spacing'))

exp_3_tables$estimate_table <- exp_3_tables$estimate_table[, -col_to_remove]
exp_3_tables$removed_value_table <- exp_3_tables$removed_value_table[ , -col_to_remove]
```
